### ISSUE TITLE
TODO list for publishing

### ISSUE THREAD

**Issue by VladimirShitov** [theislab/paperbee#8]
- [x] Merge PR from Lücken's lab
- [x] Add support for open-source LLMs, e.g. with ollama @MDLDan 
- [x] Improve the documentation @VladimirShitov , @MDLDan 
- [ ] Find a review where people selected some papers, check what is the overlap if we search with their inclusion criteria by our tool. To be discussed
- [ ] Add new platforms, e.g. Mattermost. Perhaps, better to leave to the community
